name: Deploy - Production

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [10.15.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn install
    - name: Building Project 
      run: |
        yarn ng build --prod
    - name: deploy
      run: |
        yarn netlify login
        yarn netlify deploy --dir=dist/browser --site=${{secrets.NETLIFY_SITE_ID}} --prod
      env:
        CI: true
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_TOKEN}}
